### ISSUE TITLE
Find a crash!

### ISSUE THREAD

**Issue by LvZW1895** [LibreShift/red-moon#288]
**Description information：**
This crash happened by accident when I was testing in different devices. I tried to reproduce it several times and I failed to reproduce it, but they are real. I hope they can help you to debug.

**Device info:**
 - Red Moon version (under Red Moon settings): [v3.5.0]
 - Android version (under Settings > About device): [9.0]
 - Device: [Xiaomi MI 8]
 
**Crash info:**
CRASH: com.jmstudios.redmoon (pid 26410) (dump time: 2021-03-16 11:53:53
Version: 
Long Msg: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
crashend

**Comment by smichel17** [comment]
I think this may be the same as (and thus, fixed by) https://github.com/LibreShift/red-moon/pull/285. If you have an Android development environment set up you could build the app yourself to test that, or wait until I get around to releasing a new version.
