### ISSUE TITLE
Crashes on device restart

### ISSUE THREAD

**Issue by shuvashish76** [LibreShift/red-moon#306]
**To Reproduce**
Just restart the device & Red Moon crashes with pop up message that "Red Moon stopped". Not just one time crash, it crashes on every device restart.

**Crash logs**

```
FATAL EXCEPTION: main
Process: com.jmstudios.redmoon, PID: 5132
java.lang.RuntimeException: Unable to start receiver com.jmstudios.redmoon.BootReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.jmstudios.redmoon/.filter.FilterService (has extras) }: app is in background uid UidRecord{2dec40d u0a158 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3197)
	at android.app.ActivityThread.-wrap17(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.jmstudios.redmoon/.filter.FilterService (has extras) }: app is in background uid UidRecord{2dec40d u0a158 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
	at android.app.ContextImpl.startService(ContextImpl.java:1477)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
	at com.jmstudios.redmoon.filter.Command.send(Command.kt:71)
	at com.jmstudios.redmoon.filter.Command$Companion.toggle(Command.kt:94)
	at com.jmstudios.redmoon.BootReceiver.onReceive(SystemBroadcastReceivers.kt:53)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3190)
	... 8 more
```

**Device info:**
 - Red Moon version: 3.5.0 (38) (F-Droid version)
 - Android version: 8.1.0
 - Device: Lenovo Tab4 8 Plus (TB-8704X)

**Comment by smichel17** [comment]
This is fixed in the code and will be in the next release.

**Comment by shuvashish76** [comment]
144 commits since v3.5.0, any updates regarding new release?

**Comment by smichel17** [comment]
I can do a new release any time, it takes around 2 minutes. Well, I guess plus 10-30 minutes to write the changelog.

The reason I haven't is that I merged #287 without adressing all the follow-up points, and I don't want to release a version that can leave the app in a broken state.

**Comment by smichel17** [comment]
...though, I suppose perhaps this is better than the current state, where the app does not work at all on some devices. I think I'll do a release this weekend and just note in the changelog that root mode is an unstable feature.
